<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_gws-output-pages-elements-homepage_addi_e8810c</name>
   <tag></tag>
   <elementGuidId>4010da24-ac88-4558-9420-dcac2c9707a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gws-output-pages-elements-homepage_additional_languages__als']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gws-output-pages-elements-homepage_additional_languages__als</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>665d45e3-f6d6-4de3-bedb-1ded2cee8a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vcVZ7d</value>
      <webElementGuid>853f5986-6c3b-4cd6-af1b-d008852f8a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gws-output-pages-elements-homepage_additional_languages__als</value>
      <webElementGuid>df0b6124-53e3-4d7f-9a92-a74ce2073cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>#gws-output-pages-elements-homepage_additional_languages__als{font-size:small;margin-bottom:24px}#SIvCob{color:var(--bbQxAb);display:inline-block;line-height:28px;}#SIvCob a{padding:0 3px;}.H6sW5{display:inline-block;margin:0 2px;white-space:nowrap}.z4hgWe{display:inline-block;margin:0 2px}Google tersedia dalam bahasa:  English        Basa Bali  </value>
      <webElementGuid>741ee957-1864-4653-b82f-ebc46355a88f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gws-output-pages-elements-homepage_additional_languages__als&quot;)</value>
      <webElementGuid>22369ded-95da-46eb-a426-5440fe008c24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='gws-output-pages-elements-homepage_additional_languages__als']</value>
      <webElementGuid>f4f0778d-9c73-43ce-8352-31225b384978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporkan prediksi yang tidak pantas'])[1]/following::div[8]</value>
      <webElementGuid>e96f016e-2cac-4805-b75b-f11468469cb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus'])[12]/following::div[31]</value>
      <webElementGuid>e5f591e7-4bd4-49b4-bf39-acf9cea88693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]</value>
      <webElementGuid>95cd338e-96f4-4875-b08f-d674574abdb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'gws-output-pages-elements-homepage_additional_languages__als' and (text() = '#gws-output-pages-elements-homepage_additional_languages__als{font-size:small;margin-bottom:24px}#SIvCob{color:var(--bbQxAb);display:inline-block;line-height:28px;}#SIvCob a{padding:0 3px;}.H6sW5{display:inline-block;margin:0 2px;white-space:nowrap}.z4hgWe{display:inline-block;margin:0 2px}Google tersedia dalam bahasa:  English        Basa Bali  ' or . = '#gws-output-pages-elements-homepage_additional_languages__als{font-size:small;margin-bottom:24px}#SIvCob{color:var(--bbQxAb);display:inline-block;line-height:28px;}#SIvCob a{padding:0 3px;}.H6sW5{display:inline-block;margin:0 2px;white-space:nowrap}.z4hgWe{display:inline-block;margin:0 2px}Google tersedia dalam bahasa:  English        Basa Bali  ')]</value>
      <webElementGuid>82462be5-4a84-4aeb-b2bb-ea919c138e38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
