<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Masukan aksesibilitas_jfN4p</name>
   <tag></tag>
   <elementGuidId>0d666104-5984-49e5-8aec-a11f88240fbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='logo']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.jfN4p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4c9dc68a-95b2-4438-ab96-332f5940444e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jfN4p</value>
      <webElementGuid>4bfa7912-c30c-4eb1-bfea-90f24b055cf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/branding/googlelogo/2x/googlelogo_color_92x30dp.png</value>
      <webElementGuid>5aab28a7-7ba7-4d1c-b021-c585057cc08e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Google</value>
      <webElementGuid>aa33981f-9455-4933-8f79-00d2ec38f696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>22f48c4c-ae01-43c4-8264-c0ae786098ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>92</value>
      <webElementGuid>2cfcff8f-322b-457b-8e58-16ca9d640812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csiid</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3904f8bd-33f4-4570-b2dd-03632a33d435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-atf</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>333545da-1ba6-4833-a106-8dee762e1789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logo&quot;)/img[@class=&quot;jfN4p&quot;]</value>
      <webElementGuid>12deebda-f7ac-4249-9e35-8f469ffa62e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='logo']/img</value>
      <webElementGuid>ad5d9c8e-2a87-4874-aaeb-81e6b6cf7227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Google']</value>
      <webElementGuid>83439c89-4d21-4470-b94d-da714486962b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>d1ef3209-3a6b-44bb-8617-ef39747cfaff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/branding/googlelogo/2x/googlelogo_color_92x30dp.png' and @alt = 'Google']</value>
      <webElementGuid>9b881b5d-4863-4757-82b6-90ccb9533973</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
